![](../docs/banner.png)

# Numpy

**Tshewang Rigzin, May 2022**

## Exercises

### 1.

Import numpy under the alias `np`.

In [ ]:
import numpy as np

### 2.

Create the following arrays:

1. Create an array of 5 zeros.
2. Create an array of 10 ones.
3. Create an array of 5 3.141s.
4. Create an array of the integers 1 to 20.
5. Create a 5 x 5 matrix of ones with a dtype `int`.

In [ ]:
print(f"Array of 5 Zeros: {np.zeros(5)}")
print(f"Array of 10 ones: {np.ones(10)}")
print(f"Array of 5 3.141s: {np.full(5, 3.141)}")
print(f"Array of the integers 1 to 20: {np.array(range(21))}")
print(f"5 x 5 matrix of ones with a dtype int: {np.ones((5, 5), dtype=int)}")

Array of 5 Zeros: [0. 0. 0. 0. 0.]
Array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of 5 3.141s: [3.141 3.141 3.141 3.141 3.141]
Array of the integers 1 to 20: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
5 x 5 matrix of ones with a dtype int: [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### 3.

Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [ ]:
x = np.random.randn(3, 3, 3)
x

array([[[-0.71139646, -2.06099607, -1.27560484],
        [ 0.64209225,  1.11524698,  0.45087206],
        [ 0.41857386,  0.22087499,  1.24714505]],

       [[-1.41005576,  1.30584186,  0.70822933],
        [ 0.52549526, -0.53196195,  1.57828231],
        [ 0.14968636, -2.21287426,  0.68616739]],

       [[ 0.9530045 ,  0.20995368,  1.39804344],
        [-1.75987193, -0.02461736, -0.6557997 ],
        [-0.91401727, -3.47141474, -0.62431104]]])

In [ ]:
x=x.reshape(27).shape
x

(27,)

### 4.

Create an array of 20 linearly spaced numbers between 1 and 10.

In [ ]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

### 5.

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [ ]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

```python
20
```

In [ ]:
a[3,4]

20

```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [ ]:
a[1:,3:]

array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

```python
array([ 6,  7,  8,  9, 10])
```

In [ ]:
a[1]

array([ 6,  7,  8,  9, 10])

```python
array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])
```

In [ ]:
a[2:4]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

```python
array([[ 8,  9],
       [13, 14]])
```

In [ ]:
a[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

### 6.

Calculate the sum of all the numbers in `a`.

In [ ]:
a.sum()

325

### 7.

Calculate the sum of each row in `a`.

In [ ]:
a.sum(axis=1)

array([ 15,  40,  65,  90, 115])

### 8.

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [ ]:
a[a > a.mean()]

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

### 9.

Find the location of the minimum value in the following array `b`:

In [ ]:
np.random.seed(123)
b = np.random.randn(10)
b

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025,
        1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ])

In [ ]:
b.argmin()

6

### 10.

Find the location of the maximum value in the following 2D array `c` (hint: there are many ways to do this question, but a quick search on stackoverflow.com will typically help you find the optimum solution for a problem, for example see [post](https://stackoverflow.com/questions/3584243/get-the-position-of-the-biggest-item-in-a-multi-dimensional-numpy-array)):

In [ ]:
np.random.seed(123)
c = np.random.randn(3, 2)
c

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654]])

In [ ]:
print(f"Location of Maximum Value: {np.unravel_index(c.argmax(), c.shape)}")
print(f"Maximum Value: {c.max():.2f}")

Location of Maximum Value: (2, 1)
Maximum Value: 1.65


<hr>
<hr>
<hr>